[pytest]
filterwarnings =
    ignore:.*LpVariable.dicts is deprecated.*:DeprecationWarning
    ignore:.*PULP_CBC_CMD is deprecated.*:DeprecationWarning
    ignore:.*LpProblem.constraints as a dict mapping is deprecated.*:DeprecationWarning
